let n1 = [];
let n2 = [];
let n3 = new Array();
n1.push(20);
n1.push(30);
let names = new Array();
let info = new Array();
info.push(20);
info.push("krish");
info.push(true);
let e1 = { id: 100, name: "krish", age: 20 };
let e2 = { id: 101, name: "ravi", age: 20 };
//create array obj to add or push data
let employee = new Array();
employee.push(e1);
employee.push(e2);
employee.forEach(e => console.log(e.id + " " + e.name + " " + e.age));
let r = employee.find(e => e.id == 100);
let r1 = employee.find(e => e.age == 200);
console.log(r);
console.log(r1);
